version: "3.6"
services:
    database:
      container_name: "database"
      image: "mariadb"
      environment:
        MARIADB_ROOT_PASSWORD: "password"
      volumes:
        - "./data:/var/lib/mysql"
      ports:
        - "3306:3306"
    phpmyadmin:
      image: phpmyadmin
      ports:
        - 80:80
      environment:
        - PMA_ARBITRARY=1