version: "3.6"
services:
    database:
      container_name: "database"
      image: "postgres:13.6-alpine3.15"
      environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
      volumes:
        - "./data:/var/lib/postgresql/data"
      ports:
        - "5432:5432"